### PR TITLE
Feature project newsweek

### PR DESCRIPTION
**Pull request by Rumbie-Mudzie7**
The Newsweek cloning project is mainly based on integrating the Bootstrap framework for learning purposes and necessary techniques were applied to improve on learning  Bootstrap concepts.

### CODE REVIEW

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @Rumbie-Mudzie7   :wave:
-
You have done a splendid job! :tada: Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
### The [clone](https://raw.githack.com/Rumbie-Mudzie7/project-newsweek/feature-project-newsweek/index.html) shows a good understanding and usage bootstrap 💯 

- [x] The general structure of the clone mimics the source page, however, its contents are not properly centred as it should. See the difference below 👇 

|[Source Page](https://www.newsweek.com/)|[Clone page](https://raw.githack.com/Rumbie-Mudzie7/project-newsweek/feature-project-newsweek/index.html)|
|:---:|:---:|
|source|clone|
- - [x] Since we are utilising bootstrap in this project, I'd recommend we make good use of the [`container`](https://www.w3schools.com/bootstrap4/bootstrap_containers.asp) class to centre all the pages's contents. 
-  [x] Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright).
##

- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Review by sumancrest0001 — COMMENTED** [review]
**Status: changes required 
Hello @Rumbie-Mudzie7,**
You have done a great job so far to implement changes requested by the previous TSEs and the project is looking very good to me. We are very close to getting approval for this project. Since we are doing a clone project, we have to make it similar to the original as much as we could. Therefore, we have to fix a couple of minors changes before we start working on the next project.

**Comment by Rumbie-Mudzie7** [comment]
Hie Sman Shrestha

Thank you for your feedback on my project, however, I do not understand
which minor changes you want me to change.  Please let me know which areas
I need to work on and your consideration will be greatly appreciated.

**Comment by sumancrest0001** [comment]
[REQUIRED] The editor's pick section is not breaking into a two-column section on a medium screen. 
Compare these images :point_down: 
in your project 
Screenshot from 2020-05-28 17-44-15
It should be :point_down: 
Screenshot from 2020-05-28 17-58-08


[REQUIRED] Nav bar looks congested on a small screen. Please remove unnecessary nav items.
currently :point_down: 
Screenshot from 2020-05-28 17-44-37

in the original project :point_down: 
Screenshot from 2020-05-28 18-00-31

[Note]  Subscribe button may look different as it changes constantly.

**Review by sumancrest0001 — CHANGES_REQUESTED** [review]
**Kindly make the requested changes and request another code review.
Need help or have a query regarding the review? DM me on slack Suman Shrestha**

**Happy coding !!!**

**Review by rammazzoti2000 — APPROVED** [review]
### :heavy_check_mark: Project Approved :tada: :rocket: 
Hello @sumancrest0001 you seem to have implemented all the changes required by the previous TSEs, also this project meets all requirements :clap: and so this project is approved, feel free to merge once you are ready
### Note:
- [x] The screenshot in your README file is extremely long stealling the focus on important instructions and description, please use a simple screenshot of the project, there is not need to show up all the project in a screenshot, for that there is the live demo link, right? :wink: 

##
<em>Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>
### :heavy_check_mark: Status: Project Approved

**Comment by Rumbie-Mudzie7** [comment]
Hie Rammazzoti 

Thank You for the feedback and screenshot recommendation in the readme file. Noted and much appreciated. 

Regards

**Pull request merged**
